//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcshlRateSheet
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CcshlEntities : DbContext
    {
        public CcshlEntities()
            : base("name=CcshlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LenderCategory> LenderCategories { get; set; }
        public virtual DbSet<Lender> Lenders { get; set; }
        public virtual DbSet<Plan> Plans { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<LenderPlanName> LenderPlanNames { get; set; }
        public virtual DbSet<LenderCategoriesTemp> LenderCategoriesTemps { get; set; }
        public virtual DbSet<LendersTemp> LendersTemps { get; set; }
        public virtual DbSet<PlansTemp> PlansTemps { get; set; }
        public virtual DbSet<RateHistory> RateHistories { get; set; }
        public virtual DbSet<RatesTemp> RatesTemps { get; set; }
        public virtual DbSet<LenderPlanNamesTemp> LenderPlanNamesTemps { get; set; }
    }
}
