//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CcshlRateSheet
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlansTemp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlansTemp()
        {
            this.LenderPlanNamesTemps = new HashSet<LenderPlanNamesTemp>();
            this.RatesTemps = new HashSet<RatesTemp>();
        }
    
        public int Planid { get; set; }
        public int LenderCategoryId { get; set; }
        public string PlanName { get; set; }
        public string PlanDescription { get; set; }
        public string Note { get; set; }
        public Nullable<bool> UseFHA_HighBalForBaseLoan { get; set; }
        public Nullable<decimal> FHA_HighBalForBaseLoanAmount { get; set; }
        public int NumberofRateTypes { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual LenderCategoriesTemp LenderCategoriesTemp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LenderPlanNamesTemp> LenderPlanNamesTemps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatesTemp> RatesTemps { get; set; }
    }
}
